name: 'Sync Code Scanning and JIRA'
description: "Let's you manage Code Scanning alerts from JIRA by creating an
              issue for each alert and keeping the states synced."
inputs:
  jira_url:
    description: 'URL of the JIRA instance'
    required: true
  jira_user:
    description: 'JIRA account with the required permissions'
    required: true
  jira_token:
    description: 'JIRA password or token'
    required: true
  jira_project:
    description: 'JIRA project key'
    required: true
  jira_label:
    description: 'JIRA bug label(s). Value format "red-team,blue-team,GreenTeam", or "red-team"
                  This tool will split the values entered by commas. Spaces in the double quotes
                  will be respected and saved.'
    required: false
  github_token:
    description: 'GitHub API token with the required permissions'
    required: false
    default: ${{ github.token }}
  sync_direction:
    description: 'Which direction to synchronize in ("gh2jira", "jira2gh" or "both")'
    required: false
    default: 'both'
runs:
  using: 'docker'
  image: 'Dockerfile'
